/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.106
 * Generated at: 2020-11-27 00:24:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class editRep_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Register</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("<link href=\"http://localhost:8000/trainstation/assets/css/styles.css\" rel=\"stylesheet\"/>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("body, html {\r\n");
      out.write("  height: 100%;\r\n");
      out.write("}\r\n");
      out.write("body{\r\n");
      out.write("\tbackground-color: rgb(51, 51, 51);\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-direction: column;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("}\r\n");
      out.write(".main {\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\tpadding: 2em 2em 1em 2em;\r\n");
      out.write("\twidth: 30em;\r\n");
      out.write("\tmax-width: 100%;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tborder-radius: 2%;\r\n");
      out.write("}\r\n");
      out.write(".submit{\r\n");
      out.write("\tmargin: 1em 0 1em 0;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"main\" align=\"center\">\r\n");
      out.write("\t");

		String userName = request.getParameter("userName");
		String firstName = request.getParameter("firstName");
    String lastName = request.getParameter("lastName");
    String password = request.getParameter("password");
    String SSN = request.getParameter("SSN");
    String email = request.getParameter("email");
	
      out.write("\r\n");
      out.write("\t<h3>Edit Customer Representative</h3>\r\n");
      out.write("\t<form action=\"");
      out.print( request.getContextPath() );
      out.write("/admin\" method=\"post\" class=\"register-form\">\r\n");
      out.write("\t\t<input type = \"hidden\" name=\"edit\" value=\"3\" />\r\n");
      out.write("\t\t<div class=\"form-group\" align=\"left\">\r\n");
      out.write("\t\t\t<label for=\"username\">UserName</label>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"username\" name=\"userName\" placeholder=\"Username\" class=\"form-control\" required=\"required\" value=");
      out.print( userName );
      out.write(" readonly/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\" align=\"left\">\r\n");
      out.write("\t\t\t<label for=\"first-name\">First Name</label>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"first-name\" name=\"firstName\" placeholder=\"First Name\" class=\"form-control\" value=");
      out.print( firstName );
      out.write(" required=\"required\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\" align=\"left\">\r\n");
      out.write("\t\t\t<label for=\"last-name\">Last Name</label>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"last-name\" name=\"lastName\" placeholder=\"Last Name\" class=\"form-control\" value=");
      out.print( lastName );
      out.write(" required=\"required\"></td>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\" align=\"left\">\r\n");
      out.write("\t\t\t<label for=\"password\">Password</label>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"password\" name=\"password\" placeholder=\"Password\" class=\"form-control\" value=");
      out.print( password );
      out.write(" required=\"required\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\" align=\"left\">\r\n");
      out.write("\t\t\t<label for=\"ssn\">SSN</label>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"ssn\" name=\"SSN\" placeholder=\"SSN\" class=\"form-control\" value=");
      out.print( SSN );
      out.write(" required=\"required\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\" align=\"left\">\r\n");
      out.write("\t\t\t<label id=\"email\">Email</label>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"email\" name=\"email\" placeholder=\"Email\" class=\"form-control\" value=");
      out.print( email );
      out.write(" required=\"required\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"submit\" class=\"btn btn-primary submit\">Submit</button>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<div class=\"link\">\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
