/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.106
 * Generated at: 2020-12-06 18:21:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.util.ArrayList;
import trainstation.model.TrainSchedule;

public final class schedule_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t");
 ArrayList<TrainSchedule> schedules = (ArrayList<TrainSchedule>) request.getAttribute("schedule"); 
      out.write("\r\n");
      out.write("\t\t<table class=\"table table-hover\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t    <th scope=\"col\">TrainID</th>\r\n");
      out.write("\t\t    <th scope=\"col\">StationID</th>\r\n");
      out.write("\t\t    <th scope=\"col\">Arrival Time</th>\r\n");
      out.write("\t\t    <th scope=\"col\">Depart Time</th>\r\n");
      out.write("\t\t    <th scope=\"col\">Fare</th>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t  ");
 
		  if (schedules !=null){
		  for (TrainSchedule schedule: schedules){
      out.write("\r\n");
      out.write("\t\t   <tr>\r\n");
      out.write("\t\t    <th scope=\"row\">");
      out.print( schedule.gettrainId() );
      out.write("</th>\r\n");
      out.write("\t\t    <td>");
      out.print( schedule.getstationId() );
      out.write("</td>\r\n");
      out.write("\t\t    <td>");
      out.print( schedule.getArrivalTime() );
      out.write("</td>\r\n");
      out.write("\t\t    <td>");
      out.print( schedule.getDepartTime() );
      out.write("</td>\r\n");
      out.write("\t\t    <td>$");
      out.print( schedule.getFare() );
      out.write("</td>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t  ");
}} 
      out.write("\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<form action=\"");
      out.print( request.getContextPath() );
      out.write("/reserve\" method=\"post\">\r\n");
      out.write("\t\t<div>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"form-group\" align=\"left\">\r\n");
      out.write("\t\t\t\t<label for=\"inputState\">Ticket Type</label>\r\n");
      out.write("\t      <select id=\"inputState\" class=\"form-control\" name=\"ticketType\">\r\n");
      out.write("\t\t      <option value=\"normal\" selected>Normal</option>\r\n");
      out.write("\t\t  \t\t<option value=\"children\">Children</option>\r\n");
      out.write("\t\t  \t\t<option value=\"disabled\">Disabled</option>\r\n");
      out.write("\t\t  \t\t<option value=\"senior\">Senior</option>\r\n");
      out.write("\t      </select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"form-group\" align=\"left\">\r\n");
      out.write("\t\t\t\t<label for=\"inputState\">Trip Type</label>\r\n");
      out.write("\t      <select id=\"inputState\" class=\"form-control\" name=\"tripType\">\r\n");
      out.write("\t\t      <option value=\"roundtrip\" selected>Round Trip</option>\r\n");
      out.write("\t\t  \t\t<option value=\"oneway\">1 Way</option>\r\n");
      out.write("\t      </select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t  <label for=\"example-date-input\" class=\"col-2 col-form-label\">Date</label>\r\n");
      out.write("\t\t\t  <input class=\"form-control\" type=\"date\" id=\"example-date-input\" name=\"date\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"form-group\" align=\"left\">\r\n");
      out.write("\t\t\t\t<label for=\"inputState\">User Name</label>\r\n");
      out.write("\t      <select id=\"inputState\" class=\"form-control\" name=\"userName\">\r\n");
      out.write("\t\t      <option value=\"");
      out.print( request.getAttribute("userName"));
      out.write("\" selected>");
      out.print( request.getAttribute("userName"));
      out.write("</option>\r\n");
      out.write("\t      </select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"form-group\" align=\"left\">\r\n");
      out.write("\t\t\t\t<label for=\"inputState\">TrainID</label>\r\n");
      out.write("\t      <select id=\"inputState\" class=\"form-control\" name=\"trainId\">\r\n");
      out.write("\t\t      <option value=\"");
      out.print( request.getAttribute("trainId"));
      out.write("\" selected>");
      out.print( request.getAttribute("trainId"));
      out.write("</option>\r\n");
      out.write("\t      </select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"form-group\" align=\"left\">\r\n");
      out.write("\t\t\t\t<label for=\"inputState\">Origin</label>\r\n");
      out.write("\t      <select id=\"inputState\" class=\"form-control\" name=\"origin\">\r\n");
      out.write("\t\t      <option value=\"");
      out.print( request.getAttribute("origin"));
      out.write("\" selected>");
      out.print( request.getAttribute("origin"));
      out.write("</option>\r\n");
      out.write("\t      </select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"form-group\" align=\"left\">\r\n");
      out.write("\t\t\t\t<label for=\"inputState\">Destination</label>\r\n");
      out.write("\t      <select id=\"inputState\" class=\"form-control\" name=\"destination\">\r\n");
      out.write("\t\t      <option value=\"");
      out.print( request.getAttribute("destination"));
      out.write("\" selected>");
      out.print( request.getAttribute("destination"));
      out.write("</option>\r\n");
      out.write("\t      </select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"form-group\" align=\"left\">\r\n");
      out.write("\t\t\t\t<label for=\"inputState\">Pre-Calculated Fare</label>\r\n");
      out.write("\t      <select id=\"inputState\" class=\"form-control\" name=\"fare\">\r\n");
      out.write("\t\t      <option value=\"");
      out.print( request.getAttribute("fare"));
      out.write("\" selected>");
      out.print( request.getAttribute("fare"));
      out.write("</option>\r\n");
      out.write("\t      </select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"form-group\" align=\"left\">\r\n");
      out.write("\t\t\t\t<label for=\"inputState\">Depart Time</label>\r\n");
      out.write("\t      <select id=\"inputState\" class=\"form-control\" name=\"departTime\">\r\n");
      out.write("\t\t      <option value=\"");
      out.print( request.getAttribute("departTime"));
      out.write("\" selected>");
      out.print( request.getAttribute("departTime"));
      out.write("</option>\r\n");
      out.write("\t      </select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"form-group\" align=\"left\">\r\n");
      out.write("\t\t\t\t<label for=\"inputState\">Arrival Time</label>\r\n");
      out.write("\t      <select id=\"inputState\" class=\"form-control\" name=\"arrivalTime\">\r\n");
      out.write("\t\t      <option value=\"");
      out.print( request.getAttribute("arrivalTime"));
      out.write("\" selected>");
      out.print( request.getAttribute("arrivalTime"));
      out.write("</option>\r\n");
      out.write("\t      </select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<button type=\"submit\" class=\"btn btn-primary submit\">Confirm</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
